
// COMPLEX CASES:
  // HIGH FEATURE COUNT
    // MITIGATED BY
        // GENERALIZATION
        // FEATURE CLUSTERING
  // HIGH POINT COUNT IN A SINGLE FEATURE
    // MITIGATED BY
        // GENERALIZATION
        // SEGMENTATION / CLIPPING
        // A FEATURE CAN HAVE MULTIPLE GEOMETRY SEGMENTS (A GEOMETRY SEGMENT HAS A BBOX, A NUMBER OF LINESTRINGS, AND A CROSSING STRATEGY.)

