import { zOrderIndexSpec } from "./geomey/spatialIndex/ZOrderIndex.spec";
import { rTreeSpec } from "./geomey/spatialIndex/RTree.spec";
import { meshSpec } from "./geomey/mesh/Mesh.spec";
import { coordinateSpec } from "./geomey/coordinate.spec";
import { wktSpec } from "./geomey/parser/wkt.spec";
import { relateSpec } from "./geomey/geom/relate.spec";
import { toleranceSpec } from "./geomey/Tolerance.spec";
import { relationSpec } from "./geomey/Relation.spec";
import { triangleSpec } from "./geomey/geom/Triangle.spec";
import { linearRingSpec } from "./geomey/geom/LinearRing.spec";
import { affineTransformerSpec } from "./geomey/transformer/AffineTransformer.spec";
import { pointSpec } from "./geomey/geom/Point.spec";
import { rectangleSpec } from "./geomey/geom/Rectangle.spec";

describe("Coordinate", coordinateSpec);
describe("Tolerance", toleranceSpec);
describe("Relation", relationSpec);
describe("ZOrderIndex", zOrderIndexSpec);
describe("RTree", rTreeSpec);
describe("Mesh", meshSpec);
describe("AffineTransformer", affineTransformerSpec);
describe("Wkt", wktSpec);
describe("Relate", relateSpec);
describe("Triange", triangleSpec);
describe("LinearRing", linearRingSpec);
describe("Point", pointSpec);
describe("Rectangle", rectangleSpec);
