import { zOrderIndexSpec } from "./geomey/spatialIndex/ZOrderIndex.spec";
import { rTreeSpec } from "./geomey/spatialIndex/RTree.spec";
import { meshSpec } from "./geomey/mesh/Mesh.spec";
import { coordinateSpec } from "./geomey/coordinate.spec";
import { wktSpec } from "./geomey/parser/wkt.spec";
import { relateSpec } from "./geomey/geom/relate.spec";
import { toleranceSpec } from "./geomey/Tolerance.spec";
import { relationSpec } from "./geomey/Relation.spec";
import { linearRingSpec } from "./geomey/geom/LinearRing.spec";
import { affineTransformerSpec } from "./geomey/transformer/AffineTransformer.spec";
import { pointSpec } from "./geomey/geom/Point.spec";
import { rectangleSpec } from "./geomey/geom/Rectangle.spec";
import { meshPathWalkerSpec } from "./geomey/mesh/MeshPathWalker.spec";
import { lineSegmentSpec } from "./geomey/geom/LineSegment.spec";
import { lineStringSpec } from "./geomey/geom/LineString.spec";
import { svgPathWalkerSpec } from "./geomey/path/SVGPathWalker.spec";
import { multiPointSpec } from "./geomey/geom/MultiPoint.spec";
import { multiLineStringSpec } from "./geomey/geom/MultiLineString.spec";
import { polygonSpec } from "./geomey/geom/Polygon.spec";
import { multiPolygonSpec } from "./geomey/geom/MultiPolygon.spec";
import { rectangleBuilderSpec } from "./geomey/geom/builder/RectangleBuilder.spec";
import { geoJsonSpec } from "./geomey/parser/geoJson.spec";
import { edgeSpec } from "./geomey/mesh/Edge.spec";

describe("Coordinate", coordinateSpec);
describe("Tolerance", toleranceSpec);
describe("Relation", relationSpec);
describe("ZOrderIndex", zOrderIndexSpec);
describe("RTree", rTreeSpec);
describe("Edge", edgeSpec);
describe("Mesh", meshSpec);
describe("MeshPathWalker", meshPathWalkerSpec);
describe("SVGPathWalker", svgPathWalkerSpec);
describe("AffineTransformer", affineTransformerSpec);
describe("Wkt", wktSpec);
describe("GeoJson", geoJsonSpec);
describe("Relate", relateSpec);
describe("LinearRing", linearRingSpec);
describe("Point", pointSpec);
describe("Rectangle", rectangleSpec);
describe("RectangleBuilder", rectangleBuilderSpec);
describe("LineSegment", lineSegmentSpec);
describe("LineString", lineStringSpec);
describe("MultiPoint", multiPointSpec);
describe("MultiLineString", multiLineStringSpec);
describe("Polygon", polygonSpec);
describe("MultiPolygon", multiPolygonSpec);
